site_name: MinhaTirinha - Grupo 08
site_url: https://github.com/UnBArqDsw2026-1-Turma01/2026.1-T01-G08_MinhaTirinha_Entrega_02

repo_url: https://github.com/UnBArqDsw2026-1-Turma01/2026.1-T01-G08_MinhaTirinha_Entrega_02
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UnBArqDsw2026-1-Turma01/2026.1-T01-G08_MinhaTirinha_Entrega_02

theme:
  name: material
  font:
    text: Nunito
    code: Fira Code
  palette:

    # Modo claro — tons pastéis
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: purple
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro

    # Modo escuro — pastel noturno
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro

  features:
    - navigation.tabs
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.sections

extra_css:
  - stylesheets/pastel.css

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true

nav:
  - Apresentação: index.md

  - Atas Reunião:
    - Entrega 02:
      - Ata IV: Atas/AtaReuniao04.md

  - 2. Modelagem:
    - 2.1. Modelagem Estática: Modelagem/2.1.ModelagemEstatica.md
    - 2.2. Modelagem Dinâmica: Modelagem/2.2.ModelagemDinamica.md
    - 2.3. Casos de Uso: Modelagem/2.3.ModelagemOrganizacionalCasosDeUso.md
    - 2.4. Participações - Modelagem: Modelagem/2.4.ParticipacoesModelagem.md
    - 2.5. Iniciativas Extras: Modelagem/2.5.IniciativasExtras.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
